
import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Separator } from "@/components/ui/separator";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1 container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground mb-8">Last updated: April 6, 2025</p>
          
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
              <p>
                Welcome to GenZify ("we," "our," or "us"). We are committed to protecting your privacy and personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our website and services.
              </p>
              <p>
                Please read this Privacy Policy carefully. By accessing or using our website and services, you acknowledge that you have read, understood, and agree to be bound by all the terms of this Privacy Policy.
              </p>
            </section>
            
            <Separator className="my-8" />
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">2. Information We Collect</h2>
              
              <h3 className="text-xl font-medium mt-6 mb-3">2.1 Personal Information</h3>
              <p>
                We may collect personal information that you voluntarily provide to us when you:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-2">
                <li>Register for an account</li>
                <li>Subscribe to our newsletter</li>
                <li>Request customer support</li>
                <li>Use our AI tools and services</li>
                <li>Participate in promotions or surveys</li>
                <li>Interact with our website in any other way</li>
              </ul>
              <p>
                This personal information may include:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-2">
                <li>Name</li>
                <li>Email address</li>
                <li>Phone number</li>
                <li>Billing information</li>
                <li>Username and password</li>
                <li>Profile information</li>
                <li>Preferences and settings</li>
              </ul>
              
              <h3 className="text-xl font-medium mt-6 mb-3">2.2 Usage Data</h3>
              <p>
                We automatically collect certain information when you visit, use, or navigate our website. This information does not reveal your specific identity but may include:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-2">
                <li>Device and browser information</li>
                <li>IP address</li>
                <li>Operating system</li>
                <li>Browser type and version</li>
                <li>Pages visited and actions taken</li>
                <li>Timestamps and session duration</li>
                <li>Referral source</li>
              </ul>
              
              <h3 className="text-xl font-medium mt-6 mb-3">2.3 AI-Generated Content</h3>
              <p>
                When you use our AI tools and services, we collect:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-2">
                <li>Inputs and prompts you provide to our AI systems</li>
                <li>Content generated by our AI tools based on your inputs</li>
                <li>Your interactions with and feedback on AI-generated content</li>
              </ul>
            </section>
            
            <Separator className="my-8" />
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">3. How We Use Your Information</h2>
              <p>
                We use the information we collect for various purposes, including:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-2">
                <li>Providing and maintaining our services</li>
                <li>Personalizing your experience</li>
                <li>Processing transactions and managing your account</li>
                <li>Improving our website, products, and services</li>
                <li>Analyzing usage patterns and trends</li>
                <li>Training and improving our AI models</li>
                <li>Communicating with you about updates, promotions, and support</li>
                <li>Enforcing our terms and policies</li>
                <li>Protecting against unauthorized access and fraud</li>
              </ul>
            </section>
            
            <Separator className="my-8" />
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">4. Sharing Your Information</h2>
              <p>
                We may share your information with:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-2">
                <li><strong>Service Providers:</strong> Third-party vendors who perform services on our behalf, such as payment processing, data analysis, email delivery, and customer service.</li>
                <li><strong>Business Partners:</strong> Companies we collaborate with to offer joint services or promotions.</li>
                <li><strong>Legal Requirements:</strong> When required by law, such as to comply with a subpoena or similar legal process.</li>
                <li><strong>Protection of Rights:</strong> When we believe disclosure is necessary to protect our rights, your safety, or the safety of others.</li>
                <li><strong>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets, your information may be transferred as a business asset.</li>
              </ul>
            </section>
            
            <Separator className="my-8" />
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">5. Your Privacy Rights</h2>
              <p>
                Depending on your location, you may have certain rights regarding your personal information, including:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-2">
                <li>Accessing your personal information</li>
                <li>Correcting inaccurate or incomplete information</li>
                <li>Deleting your personal information</li>
                <li>Restricting or objecting to processing</li>
                <li>Data portability</li>
                <li>Withdrawing consent</li>
              </ul>
              <p>
                To exercise these rights, please contact us at privacy@genzify.ai.
              </p>
            </section>
            
            <Separator className="my-8" />
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">6. Security</h2>
              <p>
                We implement appropriate technical and organizational measures to protect your personal information. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.
              </p>
            </section>
            
            <Separator className="my-8" />
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">7. Changes to This Privacy Policy</h2>
              <p>
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
              </p>
              <p>
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>
            </section>
            
            <Separator className="my-8" />
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">8. Contact Us</h2>
              <p>
                If you have any questions or concerns about this Privacy Policy, please contact us at:
              </p>
              <p className="mt-4">
                <strong>Email:</strong> privacy@genzify.ai<br />
                <strong>Address:</strong> 1234 Innovation Street, Tech District, San Francisco, CA 94107
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
